version: "3"
services: 
  nodeserver:
    container_name: laravel_container
    image: laravel:latest
    build: . 
    restart: unless-stopped
    depends_on: 
      - mysqldocker
    ports:
      - 80:80
      - 443:443
    networks:
      - laranet
  
  
  
  mysqldocker:
    container_name: mysqldocker
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE="laravel"
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_USER="larauser"
      - MYSQL_PASSWORD="lara123"
    networks:
      - laranet  
networks:
  laranet: